include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    # Downgrade info-level issues to ignore for cleaner analysis
    prefer_double_quotes: ignore
    prefer_int_literals: ignore
    avoid_catches_without_on_clauses: ignore
    sort_constructors_first: ignore
    avoid_annotating_with_dynamic: ignore
    unnecessary_lambdas: ignore
    always_put_control_body_on_new_line: ignore
    cast_nullable_to_non_nullable: ignore

linter:
  rules:
    # Code quality rules
    - avoid_print
    - prefer_const_constructors
    - use_key_in_widget_constructors
    - prefer_final_fields
    - avoid_unnecessary_containers
    - avoid_returning_null_for_void
    - avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - close_sinks
    - constant_identifier_names
    - control_flow_in_finally
    - empty_constructor_bodies
    - hash_and_equals
    - implementation_imports
    - non_constant_identifier_names
    # removed: package_api_docs was removed in Dart 3.7
    - package_prefixed_library_names
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_this
    - unrelated_type_equality_checks
    - valid_regexps

    # Performance rules
    - avoid_slow_async_io
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_null_aware_operators
    - prefer_spread_collections

    # Style rules
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    # - always_specify_types  # Disabled: Too strict, type inference is good
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_catches_without_on_clauses
    - avoid_empty_else
    - avoid_field_initializers_in_const_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_js_rounded_ints
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    # - avoid_redundant_argument_values  # Disabled: Sometimes explicit is clearer
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_setters_without_getters
    # - avoid_single_cascade_in_expression_statements  # Disabled: Sometimes a single cascade is fine
    - avoid_types_as_parameter_names
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_types
    # - cascade_invocations  # Disabled: Sometimes explicit calls are clearer
    - cast_nullable_to_non_nullable
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - exhaustive_cases
    - file_names
    - flutter_style_todos
    - join_return_with_assignment
    - library_names
    - library_prefixes
    # - lines_longer_than_80_chars  # Disabled: Modern screens can handle longer lines
    # removed: matching_super_constructor is not a recognized lint rule
    - no_default_cases
    - no_duplicate_case_values
    - no_logic_in_create_state
    - null_check_on_nullable_type_parameter
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_const_declarations
    - prefer_contains
    - prefer_double_quotes
    - prefer_equal_for_default_values
    # - prefer_expression_function_bodies  # Disabled: Sometimes block bodies are clearer
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_if_null_operators
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_relative_imports
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - provide_deprecation_message
    # removed: pub_package_rules is not a recognized lint rule
    - recursive_getters
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - tighten_type_of_initializing_formals
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - use_enums
    - use_function_type_syntax_for_parameters
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - void_checks
